package RoutePlanner;

import java.util.Vector;

import static RoutePlanner.TouristFactory.NUMERO_TIPOS_TURISTAS;


class ProvinceFactory {

    static final int MADRID = 0;
    static final int ALMERIA = 1;
    static final int CADIZ = 2;
    static final int CORDOBA = 3;
    static final int GRANADA = 4;
    static final int HUELVA = 5;
    static final int JAEN = 6;
    static final int MALAGA = 7;
    static final int SEVILLA = 8;
    static final int BARCELONA = 9;
    static final int GIRONA = 10;
    static final int LLEIDA = 11;
    static final int TARRAGONA = 12;
    static final int ALICANTE = 13;
    static final int CASTELLON = 14;
    static final int VALENCIA = 15;
    static final int ACORUNA = 16;
    static final int LUGO = 17;
    static final int OURENSE = 18;
    static final int PONTEVEDRA = 19;
    static final int ALAVA = 20;
    static final int GIPUZKOA = 21;
    static final int BIZKAIA = 22;

    private static Vector<Province> provinces;
    private static double[][] distanciaTransporte;
    private static double[][] probabilidadVisita;
    static int NUMERO_PROVINCIAS;


    static void inicializar() {
        crearProvincias();
        crearDistanciaTransporte();
        crearProbabilidadVisita();
    }

    private static void crearProbabilidadVisita() {
        probabilidadVisita = new double[NUMERO_PROVINCIAS][NUMERO_TIPOS_TURISTAS];

        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.GCV] = 0.59;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.GCV] = 0.263;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.GCV] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.GCV] = 0.301;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.GCV] = 0.49;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.GCV] = 0.306;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.GCV] = 0.349;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.GCV] = 0.888;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.GCV] = 0.362;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.GCV] = 0.508;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.GCV] = 1;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.GCV] = 0.703;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.GCV] = 0.839;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.GCV] = 0.586;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.GCV] = 0.407;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.GCV] = 0.203;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.GCV] = 0.438;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.GCV] = 0.395;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.GCV] = 0.397;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.GCV] = 0.437;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.GCV] = 0.663;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.GCV] = 0.403;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.GCV] = 0.301;
        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.CV] = 0.591;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.CV] = 0.262;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.CV] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.CV] = 0.359;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.CV] = 0.527;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.CV] = 0.373;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.CV] = 0.446;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.CV] = 0.956;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.CV] = 0.418;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.CV] = 0.485;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.CV] = 1;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.CV] = 0.747;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.CV] = 0.838;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.CV] = 0.643;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.CV] = 0.459;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.CV] = 0.167;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.CV] = 0.478;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.CV] = 0.471;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.CV] = 0.46;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.CV] = 0.439;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.CV] = 0.552;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.CV] = 0.337;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.CV] = 0.25;
        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.GC] = 0.402;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.GC] = 0.228;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.GC] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.GC] = 0.38;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.GC] = 0.529;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.GC] = 0.35;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.GC] = 0.428;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.GC] = 0.725;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.GC] = 0.295;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.GC] = 0.404;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.GC] = 1;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.GC] = 0.851;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.GC] = 0.919;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.GC] = 0.358;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.GC] = 0.372;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.GC] = 0.182;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.GC] = 0.434;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.GC] = 0.457;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.GC] = 0.323;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.GC] = 0.394;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.GC] = 0.723;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.GC] = 0.38;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.GC] = 0.216;
        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.GV] = 0.796;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.GV] = 0.303;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.GV] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.GV] = 0.14;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.GV] = 0.401;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.GV] = 0.173;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.GV] = 0.14;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.GV] = 0.982;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.GV] = 0.366;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.GV] = 0.654;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.GV] = 1;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.GV] = 0.485;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.GV] = 0.752;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.GV] = 0.765;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.GV] = 0.379;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.GV] = 0.27;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.GV] = 0.393;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.GV] = 0.23;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.GV] = 0.401;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.GV] = 0.48;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.GV] = 0.735;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.GV] = 0.509;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.GV] = 0.458;
        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.V] = 0.792;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.V] = 0.275;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.V] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.V] = 0.121;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.V] = 0.345;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.V] = 0.182;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.V] = 0.163;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.V] = 1;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.V] = 0.409;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.V] = 0.591;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.V] = 0.831;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.V] = 0.345;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.V] = 0.569;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.V] = 0.853;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.V] = 0.393;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.V] = 0.201;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.V] = 0.371;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.V] = 0.227;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.V] = 0.45;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.V] = 0.431;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.V] = 0.454;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.V] = 0.371;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.V] = 0.387;
        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.G] = 0.587;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.G] = 0.265;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.G] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.G] = 0.133;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.G] = 0.383;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.G] = 0.112;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.G] = 0.066;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.G] = 0.689;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.G] = 0.199;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.G] = 0.577;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.G] = 1;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.G] = 0.577;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.G] = 0.842;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.G] = 0.418;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.G] = 0.255;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.G] = 0.306;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.G] = 0.321;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.G] = 0.173;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.G] = 0.214;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.G] = 0.429;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.G] = 0.985;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.G] = 0.592;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.G] = 0.449;
        probabilidadVisita[ProvinceFactory.MADRID][TouristFactory.C] = 0.278;
        probabilidadVisita[ProvinceFactory.ALMERIA][TouristFactory.C] = 0.199;
        probabilidadVisita[ProvinceFactory.CADIZ][TouristFactory.C] = 0;
        probabilidadVisita[ProvinceFactory.CORDOBA][TouristFactory.C] = 0.524;
        probabilidadVisita[ProvinceFactory.GRANADA][TouristFactory.C] = 0.606;
        probabilidadVisita[ProvinceFactory.HUELVA][TouristFactory.C] = 0.489;
        probabilidadVisita[ProvinceFactory.JAEN][TouristFactory.C] = 0.64;
        probabilidadVisita[ProvinceFactory.MALAGA][TouristFactory.C] = 0.729;
        probabilidadVisita[ProvinceFactory.SEVILLA][TouristFactory.C] = 0.347;
        probabilidadVisita[ProvinceFactory.BARCELONA][TouristFactory.C] = 0.287;
        probabilidadVisita[ProvinceFactory.GIRONA][TouristFactory.C] = 0.975;
        probabilidadVisita[ProvinceFactory.LLEIDA][TouristFactory.C] = 1;
        probabilidadVisita[ProvinceFactory.TARRAGONA][TouristFactory.C] = 0.943;
        probabilidadVisita[ProvinceFactory.ALICANTE][TouristFactory.C] = 0.312;
        probabilidadVisita[ProvinceFactory.CASTELLON][TouristFactory.C] = 0.435;
        probabilidadVisita[ProvinceFactory.VALENCIA][TouristFactory.C] = 0.101;
        probabilidadVisita[ProvinceFactory.ACORUNA][TouristFactory.C] = 0.492;
        probabilidadVisita[ProvinceFactory.LUGO][TouristFactory.C] = 0.621;
        probabilidadVisita[ProvinceFactory.OURENSE][TouristFactory.C] = 0.382;
        probabilidadVisita[ProvinceFactory.PONTEVEDRA][TouristFactory.C] = 0.363;
        probabilidadVisita[ProvinceFactory.ALAVA][TouristFactory.C] = 0.543;
        probabilidadVisita[ProvinceFactory.GIPUZKOA][TouristFactory.C] = 0.24;
        probabilidadVisita[ProvinceFactory.BIZKAIA][TouristFactory.C] = 0.066;
    }

    static void crearProvincias() {
        provinces = new Vector<Province>();
        provinces.add(new Province(MADRID, new double[]{14.1, 18.7, 30.4}));
        provinces.add(new Province(ALMERIA, new double[]{7.8, 16.2, 14.2}));
        provinces.add(new Province(CADIZ, new double[]{2.6, 9.9, 5.6}));
        provinces.add(new Province(CORDOBA, new double[]{5.2, 26.5, 9.4}));
        provinces.add(new Province(GRANADA, new double[]{10.1, 29.1, 16.4}));
        provinces.add(new Province(HUELVA, new double[]{4.8, 25.4, 11.3}));
        provinces.add(new Province(JAEN, new double[]{3.9, 30.2, 10.7}));
        provinces.add(new Province(MALAGA, new double[]{16.1, 33, 36.9}));
        provinces.add(new Province(SEVILLA, new double[]{6.5, 20.9, 18.4}));
        provinces.add(new Province(BARCELONA, new double[]{13.9, 19, 24.1}));
        provinces.add(new Province(GIRONA, new double[]{22.2, 40.8, 31.6}));
        provinces.add(new Province(LLEIDA, new double[]{13.9, 41.6, 16.4}));
        provinces.add(new Province(TARRAGONA, new double[]{19.1, 39.8, 23.4}));
        provinces.add(new Province(ALICANTE, new double[]{10.8, 19.8, 32.3}));
        provinces.add(new Province(CASTELLON, new double[]{7.6, 23.7, 17.9}));
        provinces.add(new Province(VALENCIA, new double[]{8.6, 13.1, 11.9}));
        provinces.add(new Province(ACORUNA, new double[]{8.9, 25.5, 17.2}));
        provinces.add(new Province(LUGO, new double[]{6, 29.6, 12.7}));
        provinces.add(new Province(OURENSE, new double[]{6.8, 22, 19.7}));
        provinces.add(new Province(PONTEVEDRA, new double[]{11, 21.4, 19.1}));
        provinces.add(new Province(ALAVA, new double[]{21.9, 27.1, 19.8}));
        provinces.add(new Province(GIPUZKOA, new double[]{14.2, 17.5, 17.2}));
        provinces.add(new Province(BIZKAIA, new double[]{11.4, 12, 17.7}));

        NUMERO_PROVINCIAS = provinces.size();
    }

    private static Province getProvincia(int codigo) {
        return provinces.get(codigo);
    }

    static double[] getPreferencias(int codigo) {
        return getProvincia(codigo).getPreferencias();
    }

    static double getDistanciaEstadia(int origen, int destino) {
        return distanciaTransporte[origen][destino];
    }

    static double getProbabilidadVisita(int codigo, int grupo) {
        return probabilidadVisita[codigo][grupo];
    }

    static String getNombre(int codigo) {

        switch (codigo) {
            case 0: return "MADRID";
            case 1: return "ALMERIA";
            case 2: return "CADIZ";
            case 3: return "CORDOBA";
            case 4: return "GRANADA";
            case 5: return "HUELVA";
            case 6: return "JAEN";
            case 7: return "MALAGA";
            case 8: return "SEVILLA";
            case 9: return "BARCELONA";
            case 10: return "GIRONA";
            case 11: return "LLEIDA";
            case 12: return "TARRAGONA";
            case 13: return "ALICANTE";
            case 14: return "CASTELLON";
            case 15: return "VALENCIA";
            case 16: return "ACORUNA";
            case 17: return "LUGO";
            case 18: return "OURENSE";
            case 19: return "PONTEVEDRA";
            case 20: return "ALAVA";
            case 21: return "GIPUZKOA";
            case 22: return "BIZKAIA";
            
            default: return "ERROR DE CODIGO";
        }
    }

    private static void crearDistanciaTransporte() {
        distanciaTransporte = new double[NUMERO_PROVINCIAS][NUMERO_PROVINCIAS];

        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.MADRID] = 0.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.ALMERIA] = 563.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.CADIZ] = 663.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.CORDOBA] = 400.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.GRANADA] = 434.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.HUELVA] = 632.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.JAEN] = 335.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.MALAGA] = 544.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.SEVILLA] = 538.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.BARCELONA] = 621.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.GIRONA] = 721.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.LLEIDA] = 465.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.TARRAGONA] = 534.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.ALICANTE] = 422.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.CASTELLON] = 417.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.VALENCIA] = 352.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.ACORUNA] = 609.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.LUGO] = 511.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.OURENSE] = 521.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.PONTEVEDRA] = 623.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.ALAVA] = 351.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.GIPUZKOA] = 469.0;
        distanciaTransporte[ProvinceFactory.MADRID][ProvinceFactory.BIZKAIA] = 395.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.MADRID] = 563.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.ALMERIA] = 0.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.CADIZ] = 484.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.CORDOBA] = 332.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.GRANADA] = 166.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.HUELVA] = 516.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.JAEN] = 228.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.MALAGA] = 219.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.SEVILLA] = 422.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.BARCELONA] = 809.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.GIRONA] = 909.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.LLEIDA] = 802.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.TARRAGONA] = 711.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.ALICANTE] = 294.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.CASTELLON] = 525.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.VALENCIA] = 460.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.ACORUNA] = 1172.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.LUGO] = 1074.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.OURENSE] = 1084.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.PONTEVEDRA] = 1186.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.ALAVA] = 914.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.GIPUZKOA] = 1032.0;
        distanciaTransporte[ProvinceFactory.ALMERIA][ProvinceFactory.BIZKAIA] = 958.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.MADRID] = 663.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.ALMERIA] = 484.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.CADIZ] = 0.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.CORDOBA] = 263.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.GRANADA] = 335.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.HUELVA] = 219.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.JAEN] = 367.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.MALAGA] = 265.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.SEVILLA] = 125.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.BARCELONA] = 1284.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.GIRONA] = 1384.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.LLEIDA] = 1128.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.TARRAGONA] = 1059.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.ALICANTE] = 688.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.CASTELLON] = 873.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.VALENCIA] = 808.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.ACORUNA] = 1072.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.LUGO] = 974.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.OURENSE] = 945.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.PONTEVEDRA] = 1047.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.ALAVA] = 1014.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.GIPUZKOA] = 1132.0;
        distanciaTransporte[ProvinceFactory.CADIZ][ProvinceFactory.BIZKAIA] = 1058.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.MADRID] = 400.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.ALMERIA] = 332.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.CADIZ] = 263.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.CORDOBA] = 0.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.GRANADA] = 166.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.HUELVA] = 232.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.JAEN] = 104.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.MALAGA] = 187.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.SEVILLA] = 138.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.BARCELONA] = 908.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.GIRONA] = 1008.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.LLEIDA] = 865.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.TARRAGONA] = 796.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.ALICANTE] = 525.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.CASTELLON] = 610.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.VALENCIA] = 545.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.ACORUNA] = 995.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.LUGO] = 897.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.OURENSE] = 921.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.PONTEVEDRA] = 977.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.ALAVA] = 751.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.GIPUZKOA] = 869.0;
        distanciaTransporte[ProvinceFactory.CORDOBA][ProvinceFactory.BIZKAIA] = 795.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.MADRID] = 434.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.ALMERIA] = 166.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.CADIZ] = 335.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.CORDOBA] = 166.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.GRANADA] = 0.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.HUELVA] = 350.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.JAEN] = 99.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.MALAGA] = 129.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.SEVILLA] = 256.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.BARCELONA] = 868.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.GIRONA] = 968.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.LLEIDA] = 861.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.TARRAGONA] = 770.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.ALICANTE] = 353.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.CASTELLON] = 584.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.VALENCIA] = 519.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.ACORUNA] = 1043.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.LUGO] = 945.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.OURENSE] = 955.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.PONTEVEDRA] = 1057.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.ALAVA] = 785.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.GIPUZKOA] = 903.0;
        distanciaTransporte[ProvinceFactory.GRANADA][ProvinceFactory.BIZKAIA] = 829.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.MADRID] = 632.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.ALMERIA] = 516.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.CADIZ] = 219.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.CORDOBA] = 232.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.GRANADA] = 350.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.HUELVA] = 0.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.JAEN] = 336.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.MALAGA] = 313.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.SEVILLA] = 94.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.BARCELONA] = 1140.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.GIRONA] = 1240.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.LLEIDA] = 1097.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.TARRAGONA] = 1029.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.ALICANTE] = 703.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.CASTELLON] = 856.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.VALENCIA] = 791.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.ACORUNA] = 1006.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.LUGO] = 908.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.OURENSE] = 879.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.PONTEVEDRA] = 981.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.ALAVA] = 919.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.GIPUZKOA] = 1101.0;
        distanciaTransporte[ProvinceFactory.HUELVA][ProvinceFactory.BIZKAIA] = 939.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.MADRID] = 335.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.ALMERIA] = 228.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.CADIZ] = 367.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.CORDOBA] = 104.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.GRANADA] = 99.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.HUELVA] = 336.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.JAEN] = 0.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.MALAGA] = 209.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.SEVILLA] = 242.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.BARCELONA] = 804.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.GIRONA] = 904.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.LLEIDA] = 779.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.TARRAGONA] = 707.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.ALICANTE] = 415.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.CASTELLON] = 520.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.VALENCIA] = 455.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.ACORUNA] = 944.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.LUGO] = 846.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.OURENSE] = 856.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.PONTEVEDRA] = 957.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.ALAVA] = 686.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.GIPUZKOA] = 804.0;
        distanciaTransporte[ProvinceFactory.JAEN][ProvinceFactory.BIZKAIA] = 730.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.MADRID] = 544.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.ALMERIA] = 219.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.CADIZ] = 265.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.CORDOBA] = 187.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.GRANADA] = 129.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.HUELVA] = 313.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.JAEN] = 209.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.MALAGA] = 0.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.SEVILLA] = 219.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.BARCELONA] = 997.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.GIRONA] = 1097.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.LLEIDA] = 1009.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.TARRAGONA] = 899.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.ALICANTE] = 482.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.CASTELLON] = 713.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.VALENCIA] = 648.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.ACORUNA] = 1153.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.LUGO] = 1055.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.OURENSE] = 1065.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.PONTEVEDRA] = 1153.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.ALAVA] = 895.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.GIPUZKOA] = 1013.0;
        distanciaTransporte[ProvinceFactory.MALAGA][ProvinceFactory.BIZKAIA] = 939.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.MADRID] = 538.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.ALMERIA] = 422.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.CADIZ] = 125.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.CORDOBA] = 138.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.GRANADA] = 256.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.HUELVA] = 94.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.JAEN] = 242.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.MALAGA] = 219.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.SEVILLA] = 0.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.BARCELONA] = 1046.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.GIRONA] = 1146.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.LLEIDA] = 1003.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.TARRAGONA] = 949.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.ALICANTE] = 609.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.CASTELLON] = 762.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.VALENCIA] = 697.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.ACORUNA] = 947.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.LUGO] = 849.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.OURENSE] = 820.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.PONTEVEDRA] = 922.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.ALAVA] = 825.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.GIPUZKOA] = 1007.0;
        distanciaTransporte[ProvinceFactory.SEVILLA][ProvinceFactory.BIZKAIA] = 933.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.MADRID] = 621.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.ALMERIA] = 809.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.CADIZ] = 1284.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.CORDOBA] = 908.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.GRANADA] = 868.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.HUELVA] = 1140.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.JAEN] = 804.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.MALAGA] = 997.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.SEVILLA] = 1046.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.BARCELONA] = 0.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.GIRONA] = 100.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.LLEIDA] = 156.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.TARRAGONA] = 98.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.ALICANTE] = 515.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.CASTELLON] = 284.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.VALENCIA] = 349.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.ACORUNA] = 1118.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.LUGO] = 1020.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.OURENSE] = 1027.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.PONTEVEDRA] = 1129.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.ALAVA] = 530.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.GIPUZKOA] = 529.0;
        distanciaTransporte[ProvinceFactory.BARCELONA][ProvinceFactory.BIZKAIA] = 620.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.MADRID] = 721.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.ALMERIA] = 909.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.CADIZ] = 1384.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.CORDOBA] = 1008.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.GRANADA] = 968.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.HUELVA] = 1240.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.JAEN] = 904.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.MALAGA] = 1097.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.SEVILLA] = 1146.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.BARCELONA] = 100.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.GIRONA] = 0.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.LLEIDA] = 256.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.TARRAGONA] = 198.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.ALICANTE] = 615.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.CASTELLON] = 384.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.VALENCIA] = 449.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.ACORUNA] = 1218.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.LUGO] = 1120.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.OURENSE] = 1127.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.PONTEVEDRA] = 1229.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.ALAVA] = 630.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.GIPUZKOA] = 629.0;
        distanciaTransporte[ProvinceFactory.GIRONA][ProvinceFactory.BIZKAIA] = 720.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.MADRID] = 465.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.ALMERIA] = 802.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.CADIZ] = 1128.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.CORDOBA] = 865.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.GRANADA] = 861.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.HUELVA] = 1097.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.JAEN] = 779.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.MALAGA] = 1009.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.SEVILLA] = 1003.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.BARCELONA] = 156.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.GIRONA] = 256.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.LLEIDA] = 0.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.TARRAGONA] = 91.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.ALICANTE] = 490.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.CASTELLON] = 259.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.VALENCIA] = 324.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.ACORUNA] = 973.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.LUGO] = 875.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.OURENSE] = 871.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.PONTEVEDRA] = 973.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.ALAVA] = 374.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.GIPUZKOA] = 373.0;
        distanciaTransporte[ProvinceFactory.LLEIDA][ProvinceFactory.BIZKAIA] = 464.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.MADRID] = 534.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.ALMERIA] = 711.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.CADIZ] = 1059.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.CORDOBA] = 796.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.GRANADA] = 770.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.HUELVA] = 1029.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.JAEN] = 707.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.MALAGA] = 899.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.SEVILLA] = 949.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.BARCELONA] = 98.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.GIRONA] = 198.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.LLEIDA] = 91.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.TARRAGONA] = 0.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.ALICANTE] = 417.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.CASTELLON] = 186.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.VALENCIA] = 251.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.ACORUNA] = 1064.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.LUGO] = 966.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.OURENSE] = 962.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.PONTEVEDRA] = 1064.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.ALAVA] = 489.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.GIPUZKOA] = 464.0;
        distanciaTransporte[ProvinceFactory.TARRAGONA][ProvinceFactory.BIZKAIA] = 555.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.MADRID] = 422.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.ALMERIA] = 294.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.CADIZ] = 688.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.CORDOBA] = 525.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.GRANADA] = 353.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.HUELVA] = 703.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.JAEN] = 415.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.MALAGA] = 482.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.SEVILLA] = 609.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.BARCELONA] = 515.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.GIRONA] = 615.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.LLEIDA] = 490.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.TARRAGONA] = 417.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.ALICANTE] = 0.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.CASTELLON] = 231.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.VALENCIA] = 166.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.ACORUNA] = 1031.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.LUGO] = 933.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.OURENSE] = 943.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.PONTEVEDRA] = 1045.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.ALAVA] = 739.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.GIPUZKOA] = 766.0;
        distanciaTransporte[ProvinceFactory.ALICANTE][ProvinceFactory.BIZKAIA] = 817.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.MADRID] = 417.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.ALMERIA] = 525.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.CADIZ] = 873.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.CORDOBA] = 610.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.GRANADA] = 584.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.HUELVA] = 856.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.JAEN] = 520.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.MALAGA] = 713.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.SEVILLA] = 762.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.BARCELONA] = 284.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.GIRONA] = 384.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.LLEIDA] = 259.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.TARRAGONA] = 186.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.ALICANTE] = 231.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.CASTELLON] = 0.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.VALENCIA] = 65.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.ACORUNA] = 1026.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.LUGO] = 928.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.OURENSE] = 938.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.PONTEVEDRA] = 1040.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.ALAVA] = 574.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.GIPUZKOA] = 551.0;
        distanciaTransporte[ProvinceFactory.CASTELLON][ProvinceFactory.BIZKAIA] = 607.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.MADRID] = 352.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.ALMERIA] = 460.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.CADIZ] = 808.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.CORDOBA] = 545.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.GRANADA] = 519.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.HUELVA] = 791.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.JAEN] = 455.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.MALAGA] = 648.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.SEVILLA] = 697.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.BARCELONA] = 349.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.GIRONA] = 449.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.LLEIDA] = 324.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.TARRAGONA] = 251.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.ALICANTE] = 166.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.CASTELLON] = 65.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.VALENCIA] = 0.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.ACORUNA] = 961.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.LUGO] = 863.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.OURENSE] = 873.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.PONTEVEDRA] = 975.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.ALAVA] = 576.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.GIPUZKOA] = 594.0;
        distanciaTransporte[ProvinceFactory.VALENCIA][ProvinceFactory.BIZKAIA] = 633.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.MADRID] = 609.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.ALMERIA] = 1172.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.CADIZ] = 1072.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.CORDOBA] = 995.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.GRANADA] = 1043.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.HUELVA] = 1006.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.JAEN] = 944.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.MALAGA] = 1153.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.SEVILLA] = 947.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.BARCELONA] = 1118.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.GIRONA] = 1218.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.LLEIDA] = 973.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.TARRAGONA] = 1064.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.ALICANTE] = 1031.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.CASTELLON] = 1026.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.VALENCIA] = 961.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.ACORUNA] = 0.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.LUGO] = 98.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.OURENSE] = 175.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.PONTEVEDRA] = 121.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.ALAVA] = 549.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.GIPUZKOA] = 763.0;
        distanciaTransporte[ProvinceFactory.ACORUNA][ProvinceFactory.BIZKAIA] = 644.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.MADRID] = 511.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.ALMERIA] = 1074.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.CADIZ] = 974.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.CORDOBA] = 897.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.GRANADA] = 945.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.HUELVA] = 908.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.JAEN] = 846.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.MALAGA] = 1055.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.SEVILLA] = 849.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.BARCELONA] = 1020.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.GIRONA] = 1120.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.LLEIDA] = 875.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.TARRAGONA] = 966.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.ALICANTE] = 933.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.CASTELLON] = 928.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.VALENCIA] = 863.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.ACORUNA] = 98.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.LUGO] = 0.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.OURENSE] = 95.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.PONTEVEDRA] = 148.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.ALAVA] = 451.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.GIPUZKOA] = 665.0;
        distanciaTransporte[ProvinceFactory.LUGO][ProvinceFactory.BIZKAIA] = 546.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.MADRID] = 521.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.ALMERIA] = 1084.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.CADIZ] = 945.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.CORDOBA] = 921.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.GRANADA] = 955.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.HUELVA] = 879.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.JAEN] = 856.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.MALAGA] = 1065.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.SEVILLA] = 820.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.BARCELONA] = 1027.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.GIRONA] = 1127.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.LLEIDA] = 871.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.TARRAGONA] = 962.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.ALICANTE] = 943.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.CASTELLON] = 938.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.VALENCIA] = 873.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.ACORUNA] = 175.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.LUGO] = 95.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.OURENSE] = 0.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.PONTEVEDRA] = 102.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.ALAVA] = 561.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.GIPUZKOA] = 679.0;
        distanciaTransporte[ProvinceFactory.OURENSE][ProvinceFactory.BIZKAIA] = 605.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.MADRID] = 623.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.ALMERIA] = 1186.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.CADIZ] = 1047.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.CORDOBA] = 977.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.GRANADA] = 1057.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.HUELVA] = 981.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.JAEN] = 957.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.MALAGA] = 1153.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.SEVILLA] = 922.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.BARCELONA] = 1129.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.GIRONA] = 1229.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.LLEIDA] = 973.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.TARRAGONA] = 1064.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.ALICANTE] = 1045.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.CASTELLON] = 1040.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.VALENCIA] = 975.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.ACORUNA] = 121.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.LUGO] = 148.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.OURENSE] = 102.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.PONTEVEDRA] = 0.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.ALAVA] = 663.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.GIPUZKOA] = 781.0;
        distanciaTransporte[ProvinceFactory.PONTEVEDRA][ProvinceFactory.BIZKAIA] = 707.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.MADRID] = 351.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.ALMERIA] = 914.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.CADIZ] = 1014.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.CORDOBA] = 751.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.GRANADA] = 785.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.HUELVA] = 919.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.JAEN] = 686.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.MALAGA] = 895.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.SEVILLA] = 825.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.BARCELONA] = 530.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.GIRONA] = 630.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.LLEIDA] = 374.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.TARRAGONA] = 489.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.ALICANTE] = 739.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.CASTELLON] = 574.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.VALENCIA] = 576.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.ACORUNA] = 549.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.LUGO] = 451.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.OURENSE] = 561.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.PONTEVEDRA] = 663.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.ALAVA] = 0.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.GIPUZKOA] = 118.0;
        distanciaTransporte[ProvinceFactory.ALAVA][ProvinceFactory.BIZKAIA] = 66.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.MADRID] = 469.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.ALMERIA] = 1032.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.CADIZ] = 1132.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.CORDOBA] = 869.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.GRANADA] = 903.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.HUELVA] = 1101.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.JAEN] = 804.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.MALAGA] = 1013.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.SEVILLA] = 1007.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.BARCELONA] = 529.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.GIRONA] = 629.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.LLEIDA] = 373.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.TARRAGONA] = 464.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.ALICANTE] = 766.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.CASTELLON] = 551.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.VALENCIA] = 594.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.ACORUNA] = 763.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.LUGO] = 665.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.OURENSE] = 679.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.PONTEVEDRA] = 781.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.ALAVA] = 118.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.GIPUZKOA] = 0.0;
        distanciaTransporte[ProvinceFactory.GIPUZKOA][ProvinceFactory.BIZKAIA] = 119.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.MADRID] = 395.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.ALMERIA] = 958.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.CADIZ] = 1058.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.CORDOBA] = 795.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.GRANADA] = 829.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.HUELVA] = 939.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.JAEN] = 730.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.MALAGA] = 939.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.SEVILLA] = 933.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.BARCELONA] = 620.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.GIRONA] = 720.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.LLEIDA] = 464.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.TARRAGONA] = 555.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.ALICANTE] = 817.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.CASTELLON] = 607.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.VALENCIA] = 633.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.ACORUNA] = 644.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.LUGO] = 546.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.OURENSE] = 605.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.PONTEVEDRA] = 707.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.ALAVA] = 66.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.GIPUZKOA] = 119.0;
        distanciaTransporte[ProvinceFactory.BIZKAIA][ProvinceFactory.BIZKAIA] = 0.0;

    }

}
